[package]
name = "abc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.2.1"
druid = {version="0.8.3", features=["im", "image"]}
im = "15.1.0"
image = "0.24.7"
tokio = "1.32.0"
